---
all:
  hosts:
    debian_vm:
      ansible_host: 192.168.0.80
    fedora_vm:
      ansible_host: 192.168.0.81


deploy:
  hosts:
    debian_vm:
    fedora_vm:

backups:
  hosts:
    debian_vm:
    fedora_vm:

pihole:
  hosts:
    debian_vm:
    fedora_vm:

wg_easy:
  hosts:
    # debian_vm:
    fedora_vm:

monitoring:
  hosts:
    debian_vm:
    fedora_vm:

fedora:
  hosts:
    fedora_vm:

debian:
  hosts:
    debian_vm:
