---
all:
  hosts:
    debian_vm:
      ansible_host: 192.168.0.80


deploy:
  hosts:
    debian_vm:

backups:
  hosts:
    debian_vm:

pihole:
  hosts:
    debian_vm:
    

debian:
  hosts:
    debian_vm:
