---
wg_easy_workdir: "{{ docker_workdir }}/wg-easy"
wg_easy_image: "ghcr.io/wg-easy/wg-easy:15"
wg_easy_host: "{{ ansible_host }}"
wg_easy_wireguard_port: 51820
wg_easy_panel_port: 51821
wg_easy_caddy_image: "caddy:2.10.0-alpine"
