---
- name: Set up packages (Debian)
  ansible.builtin.import_playbook: os/package_setup_debian.yml

- name: Set up packages (Fedora)
  ansible.builtin.import_playbook: os/package_setup_fedora.yml

- name: Set up users
  ansible.builtin.import_playbook: os/user_setup.yml

- name: Set up NFS resource
  ansible.builtin.import_playbook: os/nfs_resource_setup.yml

- name: Set up backups
  ansible.builtin.import_playbook: apps/backups/deploy.yml

- name: Set up DNS
  ansible.builtin.import_playbook: apps/pi-hole/deploy.yml
