---
- name: Deploy backup scripts
  hosts: backups
  become: true
  become_user: root
  vars:
    app_workdir: "/scripts/backup"
    shrink_backup_workdir: "{{ app_workdir }}/shrink-backup"
    bk_integrity_checker_workdir: "{{ app_workdir }}/bk-integrity-checker"

  tasks:
    - name: Create scripts dir
      ansible.builtin.file:
        name: "{{ app_workdir }}"
        state: directory
        mode: "0755"

    - name: Clone shrink-backup
      ansible.builtin.git:
        repo: https://github.com/UnconnectedBedna/shrink-backup/
        dest: "{{ shrink_backup_workdir }}"
        version: v1.4

    - name: Add ntfy topic env variable to cron
      ansible.builtin.cron:
        env: true
        name: NTFY_TOPIC
        value: "{{ ntfy_topic }}"

    - name: Add shrink-backup to cron
      ansible.builtin.cron:
        name: Daily backup
        job: "{{ shrink_backup_workdir }}/shrink-backup -Utly --fix {{ backup_dest }} >/dev/null 2>&1"
        minute: 0
        hour: 2
        day: "*"
        month: "*"
        weekday: "*"
        state: present

    - name: Create bk-integrity-checker directory
      ansible.builtin.file:
        name: "{{ bk_integrity_checker_workdir }}"
        state: directory
        mode: "0755"

    - name: Copy bk-integrity-checker
      ansible.builtin.copy:
        src: "{{ repo_root }}/scripts/bk-integrity-checker/check.sh"
        dest: "{{ bk_integrity_checker_workdir }}"
        mode: "0755"

    # two hours before next backup
    - name: Add bk-integrity-checker to cron
      ansible.builtin.cron:
        name: Daily backup integrity check
        job: "{{ bk_integrity_checker_workdir }}/check.sh {{ backup_dest }} >>/var/log/bk-integrity-checker.log 2>&1"
        minute: 0
        hour: 0
        day: "*"
        month: "*"
        weekday: "*"
        state: present
