---
- name: Deploy backup scripts
  hosts: backups
  become: true

  tasks:
    - name: Create restic config directory
      ansible.builtin.file:
        path: "{{ restic_pw_file | dirname }}"
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Install restic password file
      ansible.builtin.copy:
        content: "{{ restic_pw }}\n"
        dest: "{{ restic_pw_file }}"
        owner: root
        group: root
        mode: "0600"
      no_log: true

    - name: Check if restic repo already exists
      ansible.builtin.stat:
        path: "{{ restic_repository }}/config"
      register: bk_dir

    - name: Initialise restic repo
      ansible.builtin.command:
        argv:
          - restic
          - -r
          - "{{ restic_repository }}"
          - --password-file
          - "{{ restic_pw_file }}"
          - init
      no_log: true
      when: not bk_dir.stat.exists
      changed_when: true

    - name: Add restic to cron
      ansible.builtin.cron:
        name: Daily backup
        job: >-
          restic 
          -r {{ restic_repository }}
          --password-file {{ restic_pw_file }}
          backup
          /etc
          /home
          /var/lib/docker
          /root
          >/var/log/restic.log 2>&1
        minute: 0
        hour: 2
        day: "*"
        month: "*"
        weekday: "*"
        state: present
