---
- name: Set up users and groups
  hosts: deploy
  become: true

  tasks:
    - name: Create docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Create docker user and add it to docker group
      ansible.builtin.user:
        name: docker
        group: docker
        password: "{{ docker_user_pw }}"
        generate_ssh_key: true
        state: present

    - name: Setup docker working directory
      ansible.builtin.file:
        name: "{{ docker_workdir }}"
        state: directory
        owner: docker
        mode: '0755'
