---
- name: Configure Docker YUM repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "0644"

- name: Install Docker packages on Red Hat systems
  ansible.builtin.dnf:
    name: "{{ docker_fedora_packages }}"
    update_cache: true
    state: present
